---
- name: Get status of file MIRROR_INFO_FILE
  stat: path={{ MIRROR_INFO_FILE }}
  register: st
- block:
    # Get the shell parsed values so that we are consistent with what is used
    # and don't have to do our own parsing.
    - name: Get NODEPOOL_MIRROR_HOST
      shell: source {{ MIRROR_INFO_FILE }} && echo $NODEPOOL_MIRROR_HOST
      register: mirror_host
      args:
        executable: /bin/bash
    - name: Get NODEPOOL_PYPI_MIRROR
      shell: source {{ MIRROR_INFO_FILE }} && echo $NODEPOOL_PYPI_MIRROR
      register: pypi_mirror
      args:
        executable: /bin/bash
    - include: ping_check.yaml host={{ mirror_host.stdout }}
    - include: http_check.yaml url={{ pypi_mirror.stdout }}
  when: st.stat.exists
