---
- name: Set up openvswitch requirements
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - ovs_vxlan_bridge_prereqs

- name: Set up bridge on the primary node
  hosts: primary
  gather_facts: no
  become: yes
  vars_files:
    - devstack_gate_vars.yaml
  roles:
    - ovs_vxlan_bridge_primary

- name: Set up the bridge on the sub nodes
  hosts: subnodes
  gather_facts: no
  become: yes
  vars_files:
    - devstack_gate_vars.yaml
  roles:
    - ovs_vxlan_bridge_peers
